import type { NodeFunctions } from '@/editor/compiler/types.ts'

interface Parameters {
  dynamicProperties: boolean
  declarations: readonly string[]
  helpers: string
  functions: readonly string[]
  roots: readonly NodeFunctions[]
  distance: string
}

export function sceneTemplate({
  dynamicProperties,
  declarations,
  helpers,
  functions,
  roots,
  distance,
}: Parameters): string {
  const modeComment = dynamicProperties
    ? '// Preview transforms and appearance are supplied as uniforms.'
    : "// Embed after your shader's version and precision declarations; no main/uniforms required."
  const scaledDistance = roots.length
    ? '(' + distance + ') * sceneScale'
    : '1e20'
  const layers = roots
    .map(
      (child) => `    result = sdf_over(${child.paint}(p, pixelSize), result);`
    )
    .join('\n')

  return `// Generated by SDF Studio. GLSL ES 3.00 (WebGL2).
${modeComment}
// Coordinates: scene units, Y up. Empty scene distance: 1e20.
// sdScene is geometry only; fill/stroke settings do not change its distance.
// sceneTransform maps local scene coordinates into p's coordinate space (affine mat3).
// Use mat3(1.0) for identity. Translation is in column 2; singular transforms are empty.
// Uniform scale preserves distances; nonuniform scale/shear give conservative bounds.
// sdSceneColor returns premultiplied RGBA; pixelSize is in p's units per pixel.
// Later siblings paint over earlier siblings. Booleans derive materials from their operands.
// Smooth junctions blend materials; subtraction uses the base material, including cut boundaries.

${declarations.join('\n')}
${helpers}

${functions.join('\n\n')}

float sdScene(vec2 p, mat3 sceneTransform) {
    float sceneScale = sdf_sceneScale(sceneTransform);
    if (sceneScale <= 0.0) return 1e20;
    p = (inverse(sceneTransform) * vec3(p, 1.0)).xy;
    return ${scaledDistance};
}

vec4 sdSceneColor(vec2 p, mat3 sceneTransform, float pixelSize) {
    float sceneScale = sdf_sceneScale(sceneTransform);
    if (sceneScale <= 0.0) return vec4(0.0);
    p = (inverse(sceneTransform) * vec3(p, 1.0)).xy;
    pixelSize /= sceneScale;
    vec4 result = vec4(0.0);
${layers}
    return result;
}
`
}
